AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../
      Handler: src.infrastructure.handlers.auth.post_confirmation.handler
      Runtime: python3.13
      Timeout: 5
      Environment:
        Variables:
          TABLE_NAME: LexiApp
      Policies:
        - DynamoDBCrudPolicy:
            TableName: LexiApp

Outputs:
  PostConfirmationFunctionArn:
    Value: !GetAtt PostConfirmationFunction.Arn
    Export:
      Name: PostConfirmationFunctionArn
