version = 0.1

[default.deploy.parameters]
stack_name = "lexi-backend"
resolve_s3 = true
s3_prefix = "lexi-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
